#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the servers active IPv4 IPs
# Write a Bash script that configures a server to the above requirements
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled
service nginx restart
