#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=1
while [ $i -le 20 ]
do
    if [ $i -eq 4 ]
    then
        echo "$i"
        echo "bad luck from China"
        ((i++))
    elif [ $i -eq 9 ]
    then
        echo "$i"
        echo "bad luck from Japan"
        ((i++))
    elif [ $i -eq 17 ]
    then
        echo "$i"
        echo "bad luck from Italy"
        ((i++))
    else
        echo "$i"
        ((i++))
    fi
done
