#!/usr/bin/env bash
# Create by Tomas de Castro for Holberton School 2021
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable