#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet
sudo pkill -o apache2
chmod 744 /etc/nginx/nginx.conf
sudo sed -i '3i\\n user nginx;' /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
su nginx -c 'service nginx restart'